### ISSUE TITLE
use submodule for contract

### ISSUE THREAD

**Issue by 0xmountaintop** [fluidex/fluidex-frontend#26]
+ [x] https://github.com/fluidex/fluidex-frontend/tree/master/src/contracts should be a submodule pointing to https://github.com/fluidex/contracts.demo/tree/01f24749f9f6539e7c5d932888344a04f86a0023
+ [x] have a script to "compile contract": `cd src/contracts; yarn install; npx hardhat compile`
+ [x] https://github.com/fluidex/fluidex-frontend/blob/master/src/models/ethereum.js#L2 should point to "@/contracts/artifacts/contracts/FluiDex.sol/FluiDexDemo.json"

**Comment by 0xmountaintop** [comment]
useful commands @zzq0826 
```
git submodule add ...
git submodule update --init --recursive
git pull --recurse-submodules

```

**Comment by zzq0826** [comment]
> useful commands @zzq0826
> 
> ```
> git submodule add ...
> git submodule update --init --recursive
> git pull --recurse-submodules
> ```

got it!
